version: '3'

services:
  product-service:
    build: .
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
      - MONGODB_URI=mongodb://mongo:27017/productdb
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
